export type Product = {
  id: string
  store_id: string
  name: string
  description: string
  price: number
  category: string
  image_url: string
  rating: number
  review_count: number
  in_stock: boolean
  unit?: string
  origin?: string
}

export const MOCK_PRODUCTS: Product[] = [
  // Store s1 - Afro Spice Market (Sénégal)
  {
    id: "p1",
    store_id: "s1",
    name: "Huile de Palme Rouge",
    description: "Huile de palme rouge non raffinée, pressée à froid",
    price: 12.99,
    category: "Huiles & Condiments",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 38,
    in_stock: true,
    unit: "1L",
    origin: "Côte d'Ivoire",
  },
  {
    id: "p2",
    store_id: "s1",
    name: "Farine de Manioc",
    description: "Farine de manioc fine pour gari, fufu et autres plats traditionnels",
    price: 7.99,
    category: "Farines & Céréales",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 52,
    in_stock: true,
    unit: "1kg",
    origin: "Bénin",
  },
  {
    id: "p3",
    store_id: "s1",
    name: "Piment Scotch Bonnet",
    description: "Piments frais très épicés, essentiels pour la cuisine africaine",
    price: 5.99,
    category: "Épices & Piments",
    image_url: "/african-spices.png",
    rating: 4.9,
    review_count: 67,
    in_stock: true,
    unit: "250g",
    origin: "Ghana",
  },
  {
    id: "p4",
    store_id: "s1",
    name: "Cube Maggi Africain",
    description: "Cubes d'assaisonnement saveur crevette, pack de 24",
    price: 4.99,
    category: "Assaisonnements",
    image_url: "/african-grocery.jpg",
    rating: 4.6,
    review_count: 89,
    in_stock: true,
    unit: "24 cubes",
    origin: "Nigeria",
  },
  {
    id: "p5",
    store_id: "s1",
    name: "Feuilles de Manioc Séchées",
    description: "Feuilles de manioc séchées pour saka-saka et pondu",
    price: 8.99,
    category: "Légumes Séchés",
    image_url: "/african-produce.jpg",
    rating: 4.5,
    review_count: 34,
    in_stock: true,
    unit: "500g",
    origin: "Congo",
  },
  {
    id: "p6",
    store_id: "s1",
    name: "Poudre de Gombo",
    description: "Gombo séché et moulu pour épaissir les sauces",
    price: 6.99,
    category: "Épices & Poudres",
    image_url: "/african-spices.png",
    rating: 4.7,
    review_count: 41,
    in_stock: true,
    unit: "250g",
    origin: "Mali",
  },
  {
    id: "p7",
    store_id: "s1",
    name: "Riz Parfumé Thaï",
    description: "Riz jasmin de qualité supérieure, idéal pour jollof rice",
    price: 15.99,
    category: "Riz & Céréales",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 76,
    in_stock: true,
    unit: "5kg",
    origin: "Thaïlande",
  },
  {
    id: "p8",
    store_id: "s1",
    name: "Pâte d'Arachide",
    description: "Pâte d'arachide 100% naturelle pour mafé et sauces",
    price: 9.99,
    category: "Pâtes & Purées",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 58,
    in_stock: true,
    unit: "500g",
    origin: "Sénégal",
  },
  {
    id: "p9",
    store_id: "s1",
    name: "Poisson Fumé Entier",
    description: "Poisson fumé artisanalement, saveur authentique",
    price: 18.99,
    category: "Poissons & Fruits de Mer",
    image_url: "/african-grocery.jpg",
    rating: 4.6,
    review_count: 43,
    in_stock: true,
    unit: "500g",
    origin: "Sénégal",
  },
  {
    id: "p10",
    store_id: "s1",
    name: "Fonio Précuit",
    description: "Céréale ancestrale africaine, riche en nutriments",
    price: 11.99,
    category: "Céréales",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 52,
    in_stock: true,
    unit: "1kg",
    origin: "Guinée",
  },

  // Produits génériques pour les autres magasins (90 items)
  {
    id: "p11",
    store_id: "s2",
    name: "Plantains Verts",
    description: "Bananes plantains vertes fraîches pour alloco",
    price: 3.99,
    category: "Fruits & Légumes",
    image_url: "/african-produce.jpg",
    rating: 4.7,
    review_count: 62,
    in_stock: true,
    unit: "1kg",
    origin: "Cameroun",
  },
  {
    id: "p12",
    store_id: "s2",
    name: "Ignames Fraîches",
    description: "Ignames de qualité supérieure",
    price: 6.99,
    category: "Tubercules",
    image_url: "/african-produce.jpg",
    rating: 4.6,
    review_count: 45,
    in_stock: true,
    unit: "2kg",
    origin: "Nigeria",
  },
  {
    id: "p13",
    store_id: "s2",
    name: "Manioc Frais",
    description: "Manioc frais pour fufu et autres préparations",
    price: 4.99,
    category: "Tubercules",
    image_url: "/african-produce.jpg",
    rating: 4.8,
    review_count: 71,
    in_stock: true,
    unit: "1.5kg",
    origin: "Togo",
  },
  {
    id: "p14",
    store_id: "s2",
    name: "Patates Douces Africaines",
    description: "Patates douces à chair orange",
    price: 3.49,
    category: "Tubercules",
    image_url: "/african-produce.jpg",
    rating: 4.5,
    review_count: 38,
    in_stock: true,
    unit: "1kg",
    origin: "Ghana",
  },
  {
    id: "p15",
    store_id: "s3",
    name: "Tissu Wax Hollandais",
    description: "Tissu wax authentique, motifs traditionnels",
    price: 24.99,
    category: "Tissus",
    image_url: "/african-fabrics.jpg",
    rating: 4.9,
    review_count: 89,
    in_stock: true,
    unit: "6 yards",
    origin: "Pays-Bas",
  },
  {
    id: "p16",
    store_id: "s3",
    name: "Bazin Riche Brodé",
    description: "Bazin de qualité supérieure avec broderies",
    price: 45.99,
    category: "Tissus",
    image_url: "/african-fabrics.jpg",
    rating: 4.8,
    review_count: 56,
    in_stock: true,
    unit: "5 yards",
    origin: "Mali",
  },
  {
    id: "p17",
    store_id: "s3",
    name: "Bogolan Traditionnel",
    description: "Tissu bogolan fait main, teinture naturelle",
    price: 35.99,
    category: "Tissus",
    image_url: "/african-fabrics.jpg",
    rating: 4.7,
    review_count: 42,
    in_stock: true,
    unit: "4 yards",
    origin: "Mali",
  },
  {
    id: "p18",
    store_id: "s3",
    name: "Kente Cloth",
    description: "Tissu kente ghanéen authentique",
    price: 89.99,
    category: "Tissus",
    image_url: "/african-fabrics.jpg",
    rating: 4.9,
    review_count: 67,
    in_stock: true,
    unit: "6 yards",
    origin: "Ghana",
  },
  {
    id: "p19",
    store_id: "s4",
    name: "Masque Baoulé",
    description: "Masque traditionnel baoulé sculpté à la main",
    price: 129.99,
    category: "Artisanat",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 34,
    in_stock: true,
    origin: "Côte d'Ivoire",
  },
  {
    id: "p20",
    store_id: "s4",
    name: "Statuette Ashanti",
    description: "Statuette en bois d'ébène, symbole de fertilité",
    price: 79.99,
    category: "Artisanat",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 28,
    in_stock: true,
    origin: "Ghana",
  },
  // Continue with more products for remaining stores...
  {
    id: "p21",
    store_id: "s5",
    name: "Mangues Fraîches",
    description: "Mangues Kent mûres à point",
    price: 5.99,
    category: "Fruits",
    image_url: "/african-produce.jpg",
    rating: 4.9,
    review_count: 94,
    in_stock: true,
    unit: "1kg",
    origin: "Sénégal",
  },
  {
    id: "p22",
    store_id: "s5",
    name: "Papayes",
    description: "Papayes mûres et sucrées",
    price: 4.99,
    category: "Fruits",
    image_url: "/african-produce.jpg",
    rating: 4.7,
    review_count: 67,
    in_stock: true,
    unit: "1 pièce",
    origin: "Côte d'Ivoire",
  },
  {
    id: "p23",
    store_id: "s6",
    name: "Beurre de Karité Pur",
    description: "Beurre de karité 100% naturel non raffiné",
    price: 16.99,
    category: "Soins Corps",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 156,
    in_stock: true,
    unit: "250g",
    origin: "Burkina Faso",
  },
  {
    id: "p24",
    store_id: "s6",
    name: "Savon Noir Africain",
    description: "Savon noir traditionnel pour peau et cheveux",
    price: 8.99,
    category: "Soins Corps",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 123,
    in_stock: true,
    unit: "200g",
    origin: "Ghana",
  },
  {
    id: "p25",
    store_id: "s6",
    name: "Huile de Coco Vierge",
    description: "Huile de coco pressée à froid pour cheveux",
    price: 12.99,
    category: "Soins Cheveux",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 98,
    in_stock: true,
    unit: "500ml",
    origin: "Côte d'Ivoire",
  },
  {
    id: "p26",
    store_id: "s7",
    name: "Choses d'Afrique - Roman",
    description: "Roman de Chinua Achebe, classique de la littérature africaine",
    price: 14.99,
    category: "Littérature",
    image_url: "/african-crafts.jpg",
    rating: 4.9,
    review_count: 234,
    in_stock: true,
    origin: "Nigeria",
  },
  {
    id: "p27",
    store_id: "s7",
    name: "Aya de Yopougon - BD",
    description: "Bande dessinée de Marguerite Abouet",
    price: 12.99,
    category: "Bande Dessinée",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 167,
    in_stock: true,
    origin: "Côte d'Ivoire",
  },
  {
    id: "p28",
    store_id: "s8",
    name: "Viande de Mouton",
    description: "Viande de mouton halal, morceaux choisis",
    price: 18.99,
    category: "Viandes",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 89,
    in_stock: true,
    unit: "1kg",
    origin: "France",
  },
  {
    id: "p29",
    store_id: "s8",
    name: "Poulet Fermier",
    description: "Poulet fermier halal entier",
    price: 12.99,
    category: "Volailles",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 76,
    in_stock: true,
    unit: "1.5kg",
    origin: "France",
  },
  {
    id: "p30",
    store_id: "s9",
    name: "CD Youssou N'Dour",
    description: "Album best-of du roi du mbalax",
    price: 15.99,
    category: "Musique",
    image_url: "/african-crafts.jpg",
    rating: 4.9,
    review_count: 145,
    in_stock: true,
    origin: "Sénégal",
  },
  {
    id: "p31",
    store_id: "s9",
    name: "Djembé Artisanal",
    description: "Djembé sculpté à la main, peau de chèvre",
    price: 189.99,
    category: "Instruments",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 67,
    in_stock: true,
    origin: "Mali",
  },
  {
    id: "p32",
    store_id: "s10",
    name: "Makrout aux Dattes",
    description: "Pâtisserie tunisienne aux dattes et miel",
    price: 12.99,
    category: "Pâtisseries",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 178,
    in_stock: true,
    unit: "500g",
    origin: "Tunisie",
  },
  {
    id: "p33",
    store_id: "s10",
    name: "Cornes de Gazelle",
    description: "Pâtisserie marocaine aux amandes",
    price: 14.99,
    category: "Pâtisseries",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 156,
    in_stock: true,
    unit: "500g",
    origin: "Maroc",
  },
  {
    id: "p34",
    store_id: "s11",
    name: "Collier en Or 18K",
    description: "Collier traditionnel en or massif",
    price: 899.99,
    category: "Bijoux",
    image_url: "/african-crafts.jpg",
    rating: 4.9,
    review_count: 45,
    in_stock: true,
    origin: "Ghana",
  },
  {
    id: "p35",
    store_id: "s11",
    name: "Bracelet en Argent",
    description: "Bracelet touareg en argent ciselé",
    price: 129.99,
    category: "Bijoux",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 67,
    in_stock: true,
    origin: "Niger",
  },
  {
    id: "p36",
    store_id: "s12",
    name: "Kinkeliba Séché",
    description: "Feuilles de kinkeliba pour infusion détox",
    price: 7.99,
    category: "Plantes Médicinales",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 89,
    in_stock: true,
    unit: "100g",
    origin: "Sénégal",
  },
  {
    id: "p37",
    store_id: "s12",
    name: "Moringa en Poudre",
    description: "Poudre de moringa bio, super-aliment",
    price: 15.99,
    category: "Compléments",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 134,
    in_stock: true,
    unit: "250g",
    origin: "Bénin",
  },
  {
    id: "p38",
    store_id: "s13",
    name: "Sandales en Cuir",
    description: "Sandales artisanales en cuir véritable",
    price: 45.99,
    category: "Chaussures",
    image_url: "/african-crafts.jpg",
    rating: 4.6,
    review_count: 78,
    in_stock: true,
    origin: "Éthiopie",
  },
  {
    id: "p39",
    store_id: "s13",
    name: "Babouches Marocaines",
    description: "Babouches traditionnelles brodées",
    price: 35.99,
    category: "Chaussures",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 92,
    in_stock: true,
    origin: "Maroc",
  },
  {
    id: "p40",
    store_id: "s14",
    name: "Couscous Moyen",
    description: "Couscous de semoule de blé dur",
    price: 5.99,
    category: "Céréales",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 167,
    in_stock: true,
    unit: "1kg",
    origin: "Tunisie",
  },
  {
    id: "p41",
    store_id: "s14",
    name: "Harissa Forte",
    description: "Pâte de piment tunisienne traditionnelle",
    price: 6.99,
    category: "Condiments",
    image_url: "/african-spices.png",
    rating: 4.9,
    review_count: 198,
    in_stock: true,
    unit: "200g",
    origin: "Tunisie",
  },
  {
    id: "p42",
    store_id: "s14",
    name: "Dattes Deglet Nour",
    description: "Dattes de qualité supérieure",
    price: 9.99,
    category: "Fruits Secs",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 234,
    in_stock: true,
    unit: "500g",
    origin: "Tunisie",
  },
  {
    id: "p43",
    store_id: "s15",
    name: "Tabouret Africain",
    description: "Tabouret en bois sculpté à la main",
    price: 79.99,
    category: "Meubles",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 56,
    in_stock: true,
    origin: "Kenya",
  },
  {
    id: "p44",
    store_id: "s15",
    name: "Coussin Bogolan",
    description: "Housse de coussin en tissu bogolan",
    price: 29.99,
    category: "Textiles",
    image_url: "/african-fabrics.jpg",
    rating: 4.8,
    review_count: 89,
    in_stock: true,
    origin: "Mali",
  },
  {
    id: "p45",
    store_id: "s16",
    name: "Tilapia Frais",
    description: "Poisson tilapia frais du jour",
    price: 14.99,
    category: "Poissons",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 123,
    in_stock: true,
    unit: "1kg",
    origin: "Sénégal",
  },
  {
    id: "p46",
    store_id: "s16",
    name: "Crevettes Séchées",
    description: "Petites crevettes séchées pour sauces",
    price: 12.99,
    category: "Fruits de Mer",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 98,
    in_stock: true,
    unit: "250g",
    origin: "Sénégal",
  },
  {
    id: "p47",
    store_id: "s17",
    name: "Robe Africaine Moderne",
    description: "Robe en wax, coupe contemporaine",
    price: 89.99,
    category: "Vêtements",
    image_url: "/african-fabrics.jpg",
    rating: 4.9,
    review_count: 145,
    in_stock: true,
    origin: "Côte d'Ivoire",
  },
  {
    id: "p48",
    store_id: "s17",
    name: "Chemise Homme Wax",
    description: "Chemise en tissu wax, style moderne",
    price: 59.99,
    category: "Vêtements",
    image_url: "/african-fabrics.jpg",
    rating: 4.7,
    review_count: 87,
    in_stock: true,
    origin: "Côte d'Ivoire",
  },
  {
    id: "p49",
    store_id: "s18",
    name: "Feuilles de Baobab",
    description: "Feuilles de baobab séchées, riches en vitamines",
    price: 8.99,
    category: "Plantes",
    image_url: "/african-grocery.jpg",
    rating: 4.6,
    review_count: 67,
    in_stock: true,
    unit: "100g",
    origin: "Sénégal",
  },
  {
    id: "p50",
    store_id: "s18",
    name: "Gingembre Frais",
    description: "Racine de gingembre fraîche",
    price: 4.99,
    category: "Épices Fraîches",
    image_url: "/african-spices.png",
    rating: 4.8,
    review_count: 112,
    in_stock: true,
    unit: "250g",
    origin: "Cameroun",
  },
  // Continue with products 51-100...
  {
    id: "p51",
    store_id: "s19",
    name: "Poupée Africaine",
    description: "Poupée traditionnelle en tissu wax",
    price: 24.99,
    category: "Jouets",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 89,
    in_stock: true,
    origin: "Togo",
  },
  {
    id: "p52",
    store_id: "s19",
    name: "Jeu d'Awalé",
    description: "Jeu traditionnel africain en bois",
    price: 35.99,
    category: "Jeux",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 76,
    in_stock: true,
    origin: "Côte d'Ivoire",
  },
  {
    id: "p53",
    store_id: "s20",
    name: "Café Éthiopien Yirgacheffe",
    description: "Café arabica de haute altitude",
    price: 18.99,
    category: "Café",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 234,
    in_stock: true,
    unit: "250g",
    origin: "Éthiopie",
  },
  {
    id: "p54",
    store_id: "s20",
    name: "Café Kenyan AA",
    description: "Café kenyan grade AA, notes fruitées",
    price: 19.99,
    category: "Café",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 198,
    in_stock: true,
    unit: "250g",
    origin: "Kenya",
  },
  {
    id: "p55",
    store_id: "s21",
    name: "Peinture Contemporaine",
    description: "Œuvre d'art africain contemporain",
    price: 499.99,
    category: "Art",
    image_url: "/african-crafts.jpg",
    rating: 4.9,
    review_count: 34,
    in_stock: true,
    origin: "Sénégal",
  },
  {
    id: "p56",
    store_id: "s21",
    name: "Sculpture Bronze",
    description: "Sculpture en bronze, artiste africain",
    price: 799.99,
    category: "Sculptures",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 23,
    in_stock: true,
    origin: "Bénin",
  },
  {
    id: "p57",
    store_id: "s22",
    name: "Pain de Manioc",
    description: "Pain traditionnel à base de manioc",
    price: 3.99,
    category: "Pains",
    image_url: "/african-grocery.jpg",
    rating: 4.6,
    review_count: 145,
    in_stock: true,
    unit: "500g",
    origin: "Cameroun",
  },
  {
    id: "p58",
    store_id: "s22",
    name: "Pain de Maïs",
    description: "Pain moelleux au maïs",
    price: 4.49,
    category: "Pains",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 123,
    in_stock: true,
    unit: "500g",
    origin: "Cameroun",
  },
  {
    id: "p59",
    store_id: "s23",
    name: "Parfum Oud",
    description: "Parfum oriental au bois d'oud",
    price: 45.99,
    category: "Parfums",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 167,
    in_stock: true,
    unit: "50ml",
    origin: "Maroc",
  },
  {
    id: "p60",
    store_id: "s23",
    name: "Encens Naturel",
    description: "Bâtonnets d'encens naturel",
    price: 8.99,
    category: "Encens",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 134,
    in_stock: true,
    unit: "100 bâtonnets",
    origin: "Maroc",
  },
  {
    id: "p61",
    store_id: "s24",
    name: "Smartphone Android",
    description: "Smartphone dernière génération",
    price: 299.99,
    category: "Téléphones",
    image_url: "/african-grocery.jpg",
    rating: 4.6,
    review_count: 234,
    in_stock: true,
    origin: "Chine",
  },
  {
    id: "p62",
    store_id: "s24",
    name: "Carte SIM Internationale",
    description: "Carte SIM pour appels internationaux",
    price: 15.99,
    category: "Téléphonie",
    image_url: "/african-grocery.jpg",
    rating: 4.5,
    review_count: 189,
    in_stock: true,
    origin: "Nigeria",
  },
  {
    id: "p63",
    store_id: "s25",
    name: "Sac à Main Cuir",
    description: "Sac à main en cuir artisanal",
    price: 89.99,
    category: "Sacs",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 156,
    in_stock: true,
    origin: "Mali",
  },
  {
    id: "p64",
    store_id: "s25",
    name: "Ceinture Cuir Tressé",
    description: "Ceinture en cuir tressé à la main",
    price: 39.99,
    category: "Accessoires",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 98,
    in_stock: true,
    origin: "Mali",
  },
  {
    id: "p65",
    store_id: "s26",
    name: "Quinoa Bio",
    description: "Quinoa biologique d'Afrique",
    price: 12.99,
    category: "Céréales Bio",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 178,
    in_stock: true,
    unit: "500g",
    origin: "Éthiopie",
  },
  {
    id: "p66",
    store_id: "s26",
    name: "Huile d'Argan Bio",
    description: "Huile d'argan vierge biologique",
    price: 24.99,
    category: "Huiles Bio",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 267,
    in_stock: true,
    unit: "250ml",
    origin: "Maroc",
  },
  {
    id: "p67",
    store_id: "s27",
    name: "Tresses Africaines",
    description: "Service de tressage africain",
    price: 60.0,
    category: "Services",
    image_url: "/african-crafts.jpg",
    rating: 4.9,
    review_count: 345,
    in_stock: true,
    origin: "Côte d'Ivoire",
  },
  {
    id: "p68",
    store_id: "s27",
    name: "Défrisage Naturel",
    description: "Défrisage avec produits naturels",
    price: 45.0,
    category: "Services",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 234,
    in_stock: true,
    origin: "Côte d'Ivoire",
  },
  {
    id: "p69",
    store_id: "s28",
    name: "Fromage de Chèvre",
    description: "Fromage artisanal de chèvre",
    price: 14.99,
    category: "Fromages",
    image_url: "/african-grocery.jpg",
    rating: 4.6,
    review_count: 89,
    in_stock: true,
    unit: "250g",
    origin: "Éthiopie",
  },
  {
    id: "p70",
    store_id: "s28",
    name: "Yaourt Traditionnel",
    description: "Yaourt fermenté traditionnel",
    price: 5.99,
    category: "Produits Laitiers",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 123,
    in_stock: true,
    unit: "500g",
    origin: "Éthiopie",
  },
  {
    id: "p71",
    store_id: "s29",
    name: "Masque Ancien",
    description: "Masque de collection, début XXe siècle",
    price: 1299.99,
    category: "Antiquités",
    image_url: "/african-crafts.jpg",
    rating: 4.9,
    review_count: 23,
    in_stock: true,
    origin: "Bénin",
  },
  {
    id: "p72",
    store_id: "s29",
    name: "Statue Ancienne",
    description: "Statue de collection, bois précieux",
    price: 899.99,
    category: "Antiquités",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 18,
    in_stock: true,
    origin: "Bénin",
  },
  {
    id: "p73",
    store_id: "s30",
    name: "Huile de Baobab",
    description: "Huile de baobab pressée à froid",
    price: 22.99,
    category: "Huiles Rares",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 156,
    in_stock: true,
    unit: "250ml",
    origin: "Sénégal",
  },
  {
    id: "p74",
    store_id: "s30",
    name: "Miel de Jujubier",
    description: "Miel rare de jujubier sauvage",
    price: 34.99,
    category: "Miels",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 134,
    in_stock: true,
    unit: "250g",
    origin: "Maroc",
  },
  {
    id: "p75",
    store_id: "s31",
    name: "Kora Professionnelle",
    description: "Kora à 21 cordes, instrument traditionnel",
    price: 599.99,
    category: "Instruments",
    image_url: "/african-crafts.jpg",
    rating: 4.9,
    review_count: 45,
    in_stock: true,
    origin: "Guinée",
  },
  {
    id: "p76",
    store_id: "s31",
    name: "Balafon",
    description: "Balafon traditionnel en bois",
    price: 399.99,
    category: "Instruments",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 34,
    in_stock: true,
    origin: "Mali",
  },
  {
    id: "p77",
    store_id: "s32",
    name: "Rooibos Nature",
    description: "Thé rooibos sud-africain nature",
    price: 9.99,
    category: "Thés",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 234,
    in_stock: true,
    unit: "100g",
    origin: "Afrique du Sud",
  },
  {
    id: "p78",
    store_id: "s32",
    name: "Thé Vert Marocain",
    description: "Thé vert gunpowder pour thé à la menthe",
    price: 11.99,
    category: "Thés",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 198,
    in_stock: true,
    unit: "200g",
    origin: "Maroc",
  },
  {
    id: "p79",
    store_id: "s33",
    name: "Ensemble Lingerie Wax",
    description: "Ensemble lingerie en tissu wax",
    price: 45.99,
    category: "Lingerie",
    image_url: "/african-fabrics.jpg",
    rating: 4.7,
    review_count: 89,
    in_stock: true,
    origin: "Sénégal",
  },
  {
    id: "p80",
    store_id: "s33",
    name: "Soutien-gorge Grande Taille",
    description: "Soutien-gorge adapté aux morphologies africaines",
    price: 29.99,
    category: "Lingerie",
    image_url: "/african-fabrics.jpg",
    rating: 4.8,
    review_count: 156,
    in_stock: true,
    origin: "Sénégal",
  },
  {
    id: "p81",
    store_id: "s34",
    name: "Chocolat Noir 70%",
    description: "Chocolat noir au cacao ivoirien",
    price: 8.99,
    category: "Chocolats",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 267,
    in_stock: true,
    unit: "100g",
    origin: "Côte d'Ivoire",
  },
  {
    id: "p82",
    store_id: "s34",
    name: "Pralinés Assortis",
    description: "Assortiment de pralinés au chocolat africain",
    price: 16.99,
    category: "Chocolats",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 198,
    in_stock: true,
    unit: "250g",
    origin: "Côte d'Ivoire",
  },
  {
    id: "p83",
    store_id: "s35",
    name: "Lunettes Soleil Wax",
    description: "Lunettes de soleil avec branches en wax",
    price: 79.99,
    category: "Lunettes",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 123,
    in_stock: true,
    origin: "Ghana",
  },
  {
    id: "p84",
    store_id: "s35",
    name: "Lunettes de Vue Design",
    description: "Monture design africain contemporain",
    price: 129.99,
    category: "Lunettes",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 98,
    in_stock: true,
    origin: "Ghana",
  },
  {
    id: "p85",
    store_id: "s36",
    name: "Merguez Halal",
    description: "Merguez épicées certifiées halal",
    price: 9.99,
    category: "Charcuterie",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 234,
    in_stock: true,
    unit: "500g",
    origin: "France",
  },
  {
    id: "p86",
    store_id: "s36",
    name: "Poulet Halal Découpé",
    description: "Poulet halal découpé en morceaux",
    price: 11.99,
    category: "Volailles",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 189,
    in_stock: true,
    unit: "1kg",
    origin: "France",
  },
  {
    id: "p87",
    store_id: "s37",
    name: "Coran Français-Arabe",
    description: "Coran avec traduction française",
    price: 24.99,
    category: "Livres Religieux",
    image_url: "/african-crafts.jpg",
    rating: 4.9,
    review_count: 345,
    in_stock: true,
    origin: "Égypte",
  },
  {
    id: "p88",
    store_id: "s37",
    name: "Tapis de Prière",
    description: "Tapis de prière traditionnel",
    price: 19.99,
    category: "Articles Religieux",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 267,
    in_stock: true,
    origin: "Maroc",
  },
  {
    id: "p89",
    store_id: "s38",
    name: "Fruits de la Passion",
    description: "Fruits de la passion frais et parfumés",
    price: 7.99,
    category: "Fruits Exotiques",
    image_url: "/african-produce.jpg",
    rating: 4.8,
    review_count: 178,
    in_stock: true,
    unit: "500g",
    origin: "Cameroun",
  },
  {
    id: "p90",
    store_id: "s38",
    name: "Ananas Victoria",
    description: "Ananas Victoria petit et sucré",
    price: 4.99,
    category: "Fruits Exotiques",
    image_url: "/african-produce.jpg",
    rating: 4.9,
    review_count: 234,
    in_stock: true,
    unit: "1 pièce",
    origin: "Côte d'Ivoire",
  },
  {
    id: "p91",
    store_id: "s39",
    name: "Tapis Berbère",
    description: "Tapis berbère fait main, laine naturelle",
    price: 299.99,
    category: "Tapis",
    image_url: "/african-crafts.jpg",
    rating: 4.9,
    review_count: 123,
    in_stock: true,
    unit: "200x150cm",
    origin: "Maroc",
  },
  {
    id: "p92",
    store_id: "s39",
    name: "Kilim Touareg",
    description: "Kilim touareg tissé à la main",
    price: 249.99,
    category: "Tapis",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 98,
    in_stock: true,
    unit: "180x120cm",
    origin: "Niger",
  },
  {
    id: "p93",
    store_id: "s40",
    name: "Lentilles Corail Bio",
    description: "Lentilles corail biologiques",
    price: 6.99,
    category: "Légumineuses",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 156,
    in_stock: true,
    unit: "500g",
    origin: "Éthiopie",
  },
  {
    id: "p94",
    store_id: "s40",
    name: "Pois Chiches Bio",
    description: "Pois chiches biologiques",
    price: 5.99,
    category: "Légumineuses",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 134,
    in_stock: true,
    unit: "500g",
    origin: "Maroc",
  },
  {
    id: "p95",
    store_id: "s41",
    name: "Plat Céramique",
    description: "Plat en céramique peint à la main",
    price: 45.99,
    category: "Vaisselle",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 89,
    in_stock: true,
    origin: "Mali",
  },
  {
    id: "p96",
    store_id: "s41",
    name: "Vase Terre Cuite",
    description: "Vase en terre cuite artisanal",
    price: 35.99,
    category: "Décoration",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 67,
    in_stock: true,
    origin: "Mali",
  },
  {
    id: "p97",
    store_id: "s42",
    name: "Farine de Teff",
    description: "Farine de teff sans gluten",
    price: 9.99,
    category: "Farines",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 145,
    in_stock: true,
    unit: "500g",
    origin: "Éthiopie",
  },
  {
    id: "p98",
    store_id: "s42",
    name: "Farine de Sorgho",
    description: "Farine de sorgho sans gluten",
    price: 8.99,
    category: "Farines",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 123,
    in_stock: true,
    unit: "500g",
    origin: "Nigeria",
  },
  {
    id: "p99",
    store_id: "s43",
    name: "Panier Tressé",
    description: "Panier en fibres naturelles tressées",
    price: 29.99,
    category: "Vannerie",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 98,
    in_stock: true,
    origin: "Sénégal",
  },
  {
    id: "p100",
    store_id: "s43",
    name: "Corbeille à Pain",
    description: "Corbeille à pain tressée à la main",
    price: 19.99,
    category: "Vannerie",
    image_url: "/african-crafts.jpg",
    rating: 4.6,
    review_count: 76,
    in_stock: true,
    origin: "Sénégal",
  },
]
