export type Business = {
  id: string
  name: string
  description: string
  type: "store" | "restaurant"
  image_url: string
  rating: number
  review_count: number
  country_origin: string
  category: string
  status: "open" | "closed"
  price_range?: "$" | "$$" | "$$$" | "$$$$"
  cuisine_type?: string
  delivery_available?: boolean
  click_collect?: boolean
  verified?: boolean
  opening_hours?: string
}

export const MOCK_BUSINESSES: Business[] = [
  // Restaurants africains (50)
  {
    id: "r1",
    name: "Mama Africa Restaurant",
    description:
      "Cuisine ouest-africaine authentique avec une touche moderne. Spécialités de jollof rice et poulet yassa.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.8,
    review_count: 234,
    country_origin: "Sénégal",
    category: "Restaurant",
    cuisine_type: "Ouest-africaine",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "11:00 - 23:00",
  },
  {
    id: "r2",
    name: "Le Sahel Gourmand",
    description: "Restaurant traditionnel malien proposant des plats authentiques dans une ambiance chaleureuse.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.6,
    review_count: 189,
    country_origin: "Mali",
    category: "Restaurant",
    cuisine_type: "Malienne",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 22:00",
  },
  {
    id: "r3",
    name: "Chez Fatou",
    description: "Cuisine sénégalaise familiale. Thiéboudienne, mafé et autres délices préparés avec amour.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.9,
    review_count: 312,
    country_origin: "Sénégal",
    category: "Restaurant",
    cuisine_type: "Sénégalaise",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: true,
    opening_hours: "10:00 - 21:00",
  },
  {
    id: "r4",
    name: "Abidjan Express",
    description: "Fast-food ivoirien moderne. Attiéké, alloco et grillades à emporter ou sur place.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.5,
    review_count: 156,
    country_origin: "Côte d'Ivoire",
    category: "Restaurant",
    cuisine_type: "Ivoirienne",
    status: "open",
    price_range: "$",
    delivery_available: true,
    click_collect: true,
    verified: false,
    opening_hours: "11:00 - 23:00",
  },
  {
    id: "r5",
    name: "Le Royaume du Cameroun",
    description: "Restaurant camerounais raffiné. Ndolé, poulet DG et autres spécialités dans un cadre élégant.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 198,
    country_origin: "Cameroun",
    category: "Restaurant",
    cuisine_type: "Camerounaise",
    status: "open",
    price_range: "$$$",
    delivery_available: false,
    verified: true,
    opening_hours: "18:00 - 23:00",
  },
  {
    id: "r6",
    name: "Saveurs d'Éthiopie",
    description: "Restaurant éthiopien traditionnel. Injera, wat et café éthiopien dans une ambiance authentique.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.8,
    review_count: 267,
    country_origin: "Éthiopie",
    category: "Restaurant",
    cuisine_type: "Éthiopienne",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 22:00",
  },
  {
    id: "r7",
    name: "Lagos Kitchen",
    description: "Cuisine nigériane moderne. Jollof rice, suya et puff-puff dans un cadre contemporain.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.6,
    review_count: 223,
    country_origin: "Nigeria",
    category: "Restaurant",
    cuisine_type: "Nigériane",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "11:00 - 23:00",
  },
  {
    id: "r8",
    name: "Le Maghreb Gourmand",
    description: "Restaurant maghrébin fusion. Couscous, tajines et pâtisseries orientales.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.7,
    review_count: 289,
    country_origin: "Maroc",
    category: "Restaurant",
    cuisine_type: "Marocaine",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 23:00",
  },
  {
    id: "r9",
    name: "Accra Delights",
    description: "Restaurant ghanéen familial. Banku, fufu et soupe de cacahuète préparés selon les traditions.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.5,
    review_count: 145,
    country_origin: "Ghana",
    category: "Restaurant",
    cuisine_type: "Ghanéenne",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 22:00",
  },
  {
    id: "r10",
    name: "Zanzibar Spice",
    description: "Restaurant tanzanien aux saveurs épicées. Pilau, biryani et fruits de mer frais.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.8,
    review_count: 201,
    country_origin: "Tanzanie",
    category: "Restaurant",
    cuisine_type: "Tanzanienne",
    status: "open",
    price_range: "$$$",
    delivery_available: false,
    verified: true,
    opening_hours: "18:00 - 23:00",
  },
  {
    id: "r11",
    name: "Le Petit Dakar",
    description: "Bistrot sénégalais convivial. Plats du jour et spécialités maison dans une ambiance décontractée.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.4,
    review_count: 178,
    country_origin: "Sénégal",
    category: "Restaurant",
    cuisine_type: "Sénégalaise",
    status: "open",
    price_range: "$",
    delivery_available: true,
    click_collect: true,
    verified: false,
    opening_hours: "11:00 - 21:00",
  },
  {
    id: "r12",
    name: "Kinshasa Grill",
    description: "Restaurant congolais spécialisé dans les grillades. Poisson braisé et poulet moambé.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.6,
    review_count: 167,
    country_origin: "RD Congo",
    category: "Restaurant",
    cuisine_type: "Congolaise",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 23:00",
  },
  {
    id: "r13",
    name: "Tunis Express",
    description: "Fast-food tunisien. Bricks, couscous express et sandwichs orientaux à emporter.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.3,
    review_count: 134,
    country_origin: "Tunisie",
    category: "Restaurant",
    cuisine_type: "Tunisienne",
    status: "open",
    price_range: "$",
    delivery_available: true,
    click_collect: true,
    verified: false,
    opening_hours: "10:00 - 22:00",
  },
  {
    id: "r14",
    name: "Le Palais de Bamako",
    description: "Restaurant malien haut de gamme. Cuisine raffinée dans un décor traditionnel.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.9,
    review_count: 245,
    country_origin: "Mali",
    category: "Restaurant",
    cuisine_type: "Malienne",
    status: "open",
    price_range: "$$$",
    delivery_available: false,
    verified: true,
    opening_hours: "19:00 - 23:00",
  },
  {
    id: "r15",
    name: "Soweto Soul Food",
    description: "Restaurant sud-africain moderne. Braai, bobotie et autres délices d'Afrique australe.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 212,
    country_origin: "Afrique du Sud",
    category: "Restaurant",
    cuisine_type: "Sud-africaine",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 22:00",
  },
  {
    id: "r16",
    name: "Chez Aminata",
    description: "Cuisine guinéenne familiale. Riz sauce et plats mijotés préparés avec soin.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.5,
    review_count: 156,
    country_origin: "Guinée",
    category: "Restaurant",
    cuisine_type: "Guinéenne",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 21:00",
  },
  {
    id: "r17",
    name: "Le Caire Gourmand",
    description: "Restaurant égyptien authentique. Koshari, falafel et mezze dans une ambiance orientale.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.6,
    review_count: 189,
    country_origin: "Égypte",
    category: "Restaurant",
    cuisine_type: "Égyptienne",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "11:00 - 23:00",
  },
  {
    id: "r18",
    name: "Nairobi Fusion",
    description: "Restaurant kényan fusion. Nyama choma et cuisine swahili revisitée.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.8,
    review_count: 234,
    country_origin: "Kenya",
    category: "Restaurant",
    cuisine_type: "Kényane",
    status: "open",
    price_range: "$$$",
    delivery_available: false,
    verified: true,
    opening_hours: "18:00 - 23:00",
  },
  {
    id: "r19",
    name: "Ouagadougou Saveurs",
    description: "Restaurant burkinabé traditionnel. Riz gras, tô et sauces locales.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.4,
    review_count: 123,
    country_origin: "Burkina Faso",
    category: "Restaurant",
    cuisine_type: "Burkinabé",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 21:00",
  },
  {
    id: "r20",
    name: "Alger Palace",
    description: "Restaurant algérien raffiné. Couscous royal et tajines dans un cadre élégant.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.7,
    review_count: 267,
    country_origin: "Algérie",
    category: "Restaurant",
    cuisine_type: "Algérienne",
    status: "open",
    price_range: "$$$",
    delivery_available: false,
    verified: true,
    opening_hours: "19:00 - 23:00",
  },
  {
    id: "r21",
    name: "Lomé Délices",
    description: "Restaurant togolais familial. Fufu, akoumé et sauces traditionnelles.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.5,
    review_count: 145,
    country_origin: "Togo",
    category: "Restaurant",
    cuisine_type: "Togolaise",
    status: "open",
    price_range: "$",
    delivery_available: true,
    click_collect: true,
    verified: false,
    opening_hours: "11:00 - 22:00",
  },
  {
    id: "r22",
    name: "Maputo Grill",
    description: "Restaurant mozambicain spécialisé dans les fruits de mer. Piri-piri et grillades.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.8,
    review_count: 198,
    country_origin: "Mozambique",
    category: "Restaurant",
    cuisine_type: "Mozambicaine",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 23:00",
  },
  {
    id: "r23",
    name: "Chez Mariam",
    description: "Cuisine mauritanienne authentique. Thiéboudienne et plats nomades.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.6,
    review_count: 167,
    country_origin: "Mauritanie",
    category: "Restaurant",
    cuisine_type: "Mauritanienne",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 22:00",
  },
  {
    id: "r24",
    name: "Kigali Kitchen",
    description: "Restaurant rwandais moderne. Isombe, brochettes et cuisine des mille collines.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.7,
    review_count: 189,
    country_origin: "Rwanda",
    category: "Restaurant",
    cuisine_type: "Rwandaise",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "11:00 - 22:00",
  },
  {
    id: "r25",
    name: "Le Sahara Bleu",
    description: "Restaurant touareg unique. Cuisine du désert et thé à la menthe sous une tente berbère.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.9,
    review_count: 312,
    country_origin: "Niger",
    category: "Restaurant",
    cuisine_type: "Touareg",
    status: "open",
    price_range: "$$$",
    delivery_available: false,
    verified: true,
    opening_hours: "18:00 - 23:00",
  },
  {
    id: "r26",
    name: "Cotonou Express",
    description: "Fast-food béninois. Akassa, amiwo et plats rapides à emporter.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.3,
    review_count: 134,
    country_origin: "Bénin",
    category: "Restaurant",
    cuisine_type: "Béninoise",
    status: "open",
    price_range: "$",
    delivery_available: true,
    click_collect: true,
    verified: false,
    opening_hours: "10:00 - 22:00",
  },
  {
    id: "r27",
    name: "Luanda Flavors",
    description: "Restaurant angolais authentique. Muamba de galinha et calulu dans une ambiance chaleureuse.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.6,
    review_count: 178,
    country_origin: "Angola",
    category: "Restaurant",
    cuisine_type: "Angolaise",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 22:00",
  },
  {
    id: "r28",
    name: "Kampala Bites",
    description: "Restaurant ougandais moderne. Matoke, luwombo et cuisine des grands lacs.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.5,
    review_count: 156,
    country_origin: "Ouganda",
    category: "Restaurant",
    cuisine_type: "Ougandaise",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 22:00",
  },
  {
    id: "r29",
    name: "Le Maghreb Royal",
    description: "Restaurant marocain haut de gamme. Pastilla, tajines et couscous royal.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.9,
    review_count: 289,
    country_origin: "Maroc",
    category: "Restaurant",
    cuisine_type: "Marocaine",
    status: "open",
    price_range: "$$$$",
    delivery_available: false,
    verified: true,
    opening_hours: "19:00 - 23:00",
  },
  {
    id: "r30",
    name: "Bissau Saveurs",
    description: "Restaurant bissau-guinéen familial. Caldo de mancarra et plats créoles.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.4,
    review_count: 123,
    country_origin: "Guinée-Bissau",
    category: "Restaurant",
    cuisine_type: "Bissau-guinéenne",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 21:00",
  },
  {
    id: "r31",
    name: "Harare Grill House",
    description: "Restaurant zimbabwéen spécialisé dans les grillades. Sadza et viandes braisées.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 201,
    country_origin: "Zimbabwe",
    category: "Restaurant",
    cuisine_type: "Zimbabwéenne",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 23:00",
  },
  {
    id: "r32",
    name: "Libreville Délices",
    description: "Restaurant gabonais authentique. Nyembwe et poisson fumé dans une ambiance tropicale.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.6,
    review_count: 167,
    country_origin: "Gabon",
    category: "Restaurant",
    cuisine_type: "Gabonaise",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 22:00",
  },
  {
    id: "r33",
    name: "Chez Khadija",
    description: "Cuisine soudanaise traditionnelle. Ful medames, kisra et ragoûts épicés.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.5,
    review_count: 145,
    country_origin: "Soudan",
    category: "Restaurant",
    cuisine_type: "Soudanaise",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 21:00",
  },
  {
    id: "r34",
    name: "Lusaka Kitchen",
    description: "Restaurant zambien moderne. Nshima et relish dans un cadre contemporain.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.6,
    review_count: 178,
    country_origin: "Zambie",
    category: "Restaurant",
    cuisine_type: "Zambienne",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "11:00 - 22:00",
  },
  {
    id: "r35",
    name: "Antananarivo Spice",
    description: "Restaurant malgache aux saveurs uniques. Romazava, ravitoto et cuisine de l'océan Indien.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.8,
    review_count: 223,
    country_origin: "Madagascar",
    category: "Restaurant",
    cuisine_type: "Malgache",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 22:00",
  },
  {
    id: "r36",
    name: "N'Djamena Grill",
    description: "Restaurant tchadien spécialisé dans les grillades. Boule et sauces locales.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.4,
    review_count: 134,
    country_origin: "Tchad",
    category: "Restaurant",
    cuisine_type: "Tchadienne",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 22:00",
  },
  {
    id: "r37",
    name: "Bangui Saveurs",
    description: "Restaurant centrafricain familial. Saka-saka et plats traditionnels.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.5,
    review_count: 123,
    country_origin: "Centrafrique",
    category: "Restaurant",
    cuisine_type: "Centrafricaine",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 21:00",
  },
  {
    id: "r38",
    name: "Windhoek Braai",
    description: "Restaurant namibien spécialisé dans le braai. Viandes grillées et biltong.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.7,
    review_count: 189,
    country_origin: "Namibie",
    category: "Restaurant",
    cuisine_type: "Namibienne",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 23:00",
  },
  {
    id: "r39",
    name: "Gaborone Flavors",
    description: "Restaurant botswanais moderne. Seswaa et cuisine du Kalahari.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.6,
    review_count: 156,
    country_origin: "Botswana",
    category: "Restaurant",
    cuisine_type: "Botswanaise",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "11:00 - 22:00",
  },
  {
    id: "r40",
    name: "Mbabane Kitchen",
    description: "Restaurant swazi authentique. Sishwala et plats traditionnels du Swaziland.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.5,
    review_count: 134,
    country_origin: "Eswatini",
    category: "Restaurant",
    cuisine_type: "Swazie",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 21:00",
  },
  {
    id: "r41",
    name: "Maseru Délices",
    description: "Restaurant lesothan familial. Papa et chakalaka dans une ambiance conviviale.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.4,
    review_count: 123,
    country_origin: "Lesotho",
    category: "Restaurant",
    cuisine_type: "Lesothane",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 21:00",
  },
  {
    id: "r42",
    name: "Banjul Bites",
    description: "Restaurant gambien moderne. Domoda et benachin revisités.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.6,
    review_count: 167,
    country_origin: "Gambie",
    category: "Restaurant",
    cuisine_type: "Gambienne",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "11:00 - 22:00",
  },
  {
    id: "r43",
    name: "Freetown Flavors",
    description: "Restaurant sierra-léonais authentique. Cassava leaves et plats créoles.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.5,
    review_count: 145,
    country_origin: "Sierra Leone",
    category: "Restaurant",
    cuisine_type: "Sierra-léonaise",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 21:00",
  },
  {
    id: "r44",
    name: "Monrovia Kitchen",
    description: "Restaurant libérien familial. Jollof rice et plats traditionnels.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.4,
    review_count: 134,
    country_origin: "Liberia",
    category: "Restaurant",
    cuisine_type: "Libérienne",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 21:00",
  },
  {
    id: "r45",
    name: "Djibouti Spice",
    description: "Restaurant djiboutien aux influences multiples. Skoudehkaris et cuisine de la mer Rouge.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 178,
    country_origin: "Djibouti",
    category: "Restaurant",
    cuisine_type: "Djiboutienne",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 22:00",
  },
  {
    id: "r46",
    name: "Asmara Café",
    description: "Restaurant érythréen traditionnel. Injera, zigni et café érythréen.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.6,
    review_count: 156,
    country_origin: "Érythrée",
    category: "Restaurant",
    cuisine_type: "Érythréenne",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "11:00 - 22:00",
  },
  {
    id: "r47",
    name: "Mogadiscio Grill",
    description: "Restaurant somalien spécialisé dans les grillades. Bariis iskukaris et viandes épicées.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.5,
    review_count: 145,
    country_origin: "Somalie",
    category: "Restaurant",
    cuisine_type: "Somalienne",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: false,
    opening_hours: "12:00 - 22:00",
  },
  {
    id: "r48",
    name: "Brazzaville Délices",
    description: "Restaurant congolais (Brazzaville) familial. Saka-saka et poisson salé.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.6,
    review_count: 167,
    country_origin: "Congo",
    category: "Restaurant",
    cuisine_type: "Congolaise",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 21:00",
  },
  {
    id: "r49",
    name: "Malabo Saveurs",
    description: "Restaurant équato-guinéen authentique. Succotash et plats créoles.",
    type: "restaurant",
    image_url: "/african-restaurant.png",
    rating: 4.4,
    review_count: 123,
    country_origin: "Guinée équatoriale",
    category: "Restaurant",
    cuisine_type: "Équato-guinéenne",
    status: "open",
    price_range: "$",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 21:00",
  },
  {
    id: "r50",
    name: "São Tomé Flavors",
    description: "Restaurant santoméen aux saveurs créoles. Calulu et poissons de l'Atlantique.",
    type: "restaurant",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.7,
    review_count: 189,
    country_origin: "São Tomé-et-Príncipe",
    category: "Restaurant",
    cuisine_type: "Santoméenne",
    status: "open",
    price_range: "$$",
    delivery_available: true,
    verified: true,
    opening_hours: "12:00 - 22:00",
  },

  // Commerces africains (50)
  {
    id: "s1",
    name: "Afro Spice Market",
    description:
      "Épicerie spécialisée dans les épices africaines. Plus de 200 variétés d'épices, condiments et ingrédients traditionnels.",
    type: "store",
    image_url: "/african-spices.png",
    rating: 4.8,
    review_count: 312,
    country_origin: "Sénégal",
    category: "Épicerie",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "9:00 - 20:00",
  },
  {
    id: "s2",
    name: "Sahel Grocery",
    description: "Supermarché africain complet. Produits frais, surgelés et épicerie sèche d'Afrique de l'Ouest.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 267,
    country_origin: "Mali",
    category: "Supermarché",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "8:00 - 21:00",
  },
  {
    id: "s3",
    name: "Wax & Tissus Africains",
    description: "Boutique de tissus africains authentiques. Wax, bazin, bogolan et accessoires de mode.",
    type: "store",
    image_url: "/african-fabrics.jpg",
    rating: 4.9,
    review_count: 234,
    country_origin: "Côte d'Ivoire",
    category: "Mode",
    status: "open",
    delivery_available: true,
    verified: true,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s4",
    name: "Artisanat du Sahel",
    description: "Boutique d'artisanat africain. Sculptures, bijoux, masques et objets décoratifs authentiques.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.6,
    review_count: 189,
    country_origin: "Burkina Faso",
    category: "Artisanat",
    status: "open",
    delivery_available: false,
    verified: true,
    opening_hours: "10:00 - 18:00",
  },
  {
    id: "s5",
    name: "Marché Tropical",
    description: "Épicerie exotique spécialisée dans les produits frais. Fruits, légumes et tubercules d'Afrique.",
    type: "store",
    image_url: "/african-produce.jpg",
    rating: 4.5,
    review_count: 198,
    country_origin: "Cameroun",
    category: "Fruits & Légumes",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: false,
    opening_hours: "7:00 - 20:00",
  },
  {
    id: "s6",
    name: "Beauté Noire",
    description:
      "Boutique de cosmétiques afro. Produits capillaires, soins de la peau et maquillage pour peaux noires.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 278,
    country_origin: "Nigeria",
    category: "Cosmétiques",
    status: "open",
    delivery_available: true,
    verified: true,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s7",
    name: "Librairie Africaine",
    description: "Librairie spécialisée dans la littérature africaine. Romans, essais, BD et livres pour enfants.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 156,
    country_origin: "Sénégal",
    category: "Librairie",
    status: "open",
    delivery_available: true,
    verified: true,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s8",
    name: "Boucherie Halal Africaine",
    description: "Boucherie halal spécialisée dans les viandes africaines. Mouton, chèvre et volailles.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.6,
    review_count: 223,
    country_origin: "Mali",
    category: "Boucherie",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "8:00 - 20:00",
  },
  {
    id: "s9",
    name: "Musique d'Afrique",
    description: "Magasin de musique africaine. CD, vinyles, instruments traditionnels et accessoires.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.5,
    review_count: 134,
    country_origin: "Congo",
    category: "Musique",
    status: "open",
    delivery_available: true,
    verified: false,
    opening_hours: "11:00 - 19:00",
  },
  {
    id: "s10",
    name: "Pâtisserie Orientale",
    description: "Pâtisserie spécialisée dans les douceurs maghrébines. Makrout, cornes de gazelle et gâteaux au miel.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 289,
    country_origin: "Maroc",
    category: "Pâtisserie",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "8:00 - 20:00",
  },
  {
    id: "s11",
    name: "Bijouterie Africaine",
    description: "Bijouterie spécialisée dans les bijoux africains. Or, argent et pierres précieuses.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 201,
    country_origin: "Ghana",
    category: "Bijouterie",
    status: "open",
    delivery_available: false,
    verified: true,
    opening_hours: "10:00 - 18:00",
  },
  {
    id: "s12",
    name: "Pharmacie Traditionnelle",
    description: "Pharmacie de médecine traditionnelle africaine. Plantes médicinales et remèdes naturels.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.4,
    review_count: 167,
    country_origin: "Bénin",
    category: "Santé",
    status: "open",
    delivery_available: true,
    verified: false,
    opening_hours: "9:00 - 19:00",
  },
  {
    id: "s13",
    name: "Chaussures Africaines",
    description: "Boutique de chaussures et sandales africaines. Modèles traditionnels et contemporains.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.6,
    review_count: 178,
    country_origin: "Éthiopie",
    category: "Chaussures",
    status: "open",
    delivery_available: true,
    verified: true,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s14",
    name: "Épicerie du Maghreb",
    description: "Épicerie maghrébine complète. Couscous, harissa, dattes et produits du Maghreb.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 245,
    country_origin: "Tunisie",
    category: "Épicerie",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "8:00 - 21:00",
  },
  {
    id: "s15",
    name: "Décoration Africaine",
    description: "Boutique de décoration intérieure africaine. Meubles, textiles et objets décoratifs.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 212,
    country_origin: "Kenya",
    category: "Décoration",
    status: "open",
    delivery_available: false,
    verified: true,
    opening_hours: "10:00 - 18:00",
  },
  {
    id: "s16",
    name: "Poissonnerie Africaine",
    description: "Poissonnerie spécialisée dans les poissons africains. Poissons frais, fumés et séchés.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.5,
    review_count: 189,
    country_origin: "Sénégal",
    category: "Poissonnerie",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "7:00 - 19:00",
  },
  {
    id: "s17",
    name: "Mode Africaine Moderne",
    description: "Boutique de prêt-à-porter africain contemporain. Créations modernes inspirées des traditions.",
    type: "store",
    image_url: "/african-fabrics.jpg",
    rating: 4.9,
    review_count: 267,
    country_origin: "Côte d'Ivoire",
    category: "Mode",
    status: "open",
    delivery_available: true,
    verified: true,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s18",
    name: "Herboristerie Africaine",
    description: "Herboristerie traditionnelle. Plantes médicinales, tisanes et produits naturels d'Afrique.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.6,
    review_count: 156,
    country_origin: "Cameroun",
    category: "Herboristerie",
    status: "open",
    delivery_available: true,
    verified: false,
    opening_hours: "9:00 - 19:00",
  },
  {
    id: "s19",
    name: "Jouets Africains",
    description: "Boutique de jouets et jeux africains. Jouets traditionnels et éducatifs pour enfants.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 198,
    country_origin: "Togo",
    category: "Jouets",
    status: "open",
    delivery_available: true,
    verified: true,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s20",
    name: "Café Africain",
    description: "Torréfacteur de café africain. Cafés d'Éthiopie, Kenya, Rwanda et autres origines.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 234,
    country_origin: "Éthiopie",
    category: "Café & Thé",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "9:00 - 19:00",
  },
  {
    id: "s21",
    name: "Galerie d'Art Africain",
    description: "Galerie d'art contemporain africain. Peintures, sculptures et photographies d'artistes africains.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.9,
    review_count: 178,
    country_origin: "Sénégal",
    category: "Art",
    status: "open",
    delivery_available: false,
    verified: true,
    opening_hours: "11:00 - 19:00",
  },
  {
    id: "s22",
    name: "Boulangerie Africaine",
    description: "Boulangerie spécialisée dans les pains africains. Pain de manioc, pain de maïs et viennoiseries.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.6,
    review_count: 223,
    country_origin: "Cameroun",
    category: "Boulangerie",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "6:00 - 20:00",
  },
  {
    id: "s23",
    name: "Parfumerie Orientale",
    description: "Parfumerie spécialisée dans les parfums orientaux et africains. Huiles essentielles et encens.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 189,
    country_origin: "Maroc",
    category: "Parfumerie",
    status: "open",
    delivery_available: true,
    verified: true,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s24",
    name: "Électronique Africaine",
    description: "Magasin d'électronique et téléphonie. Smartphones, accessoires et cartes de recharge.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.5,
    review_count: 267,
    country_origin: "Nigeria",
    category: "Électronique",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "9:00 - 20:00",
  },
  {
    id: "s25",
    name: "Maroquinerie Africaine",
    description: "Boutique de maroquinerie artisanale. Sacs, ceintures et accessoires en cuir africain.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 201,
    country_origin: "Mali",
    category: "Maroquinerie",
    status: "open",
    delivery_available: true,
    verified: true,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s26",
    name: "Épicerie Bio Africaine",
    description: "Épicerie bio spécialisée dans les produits africains biologiques. Céréales, légumineuses et huiles.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 234,
    country_origin: "Burkina Faso",
    category: "Bio",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "9:00 - 19:00",
  },
  {
    id: "s27",
    name: "Salon de Coiffure Afro",
    description: "Salon de coiffure spécialisé dans les coiffures afro. Tresses, nattes et soins capillaires.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 312,
    country_origin: "Côte d'Ivoire",
    category: "Coiffure",
    status: "open",
    delivery_available: false,
    verified: true,
    opening_hours: "9:00 - 20:00",
  },
  {
    id: "s28",
    name: "Fromagerie Africaine",
    description: "Fromagerie artisanale africaine. Fromages de chèvre et produits laitiers traditionnels.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.6,
    review_count: 156,
    country_origin: "Éthiopie",
    category: "Fromagerie",
    status: "open",
    delivery_available: true,
    verified: false,
    opening_hours: "8:00 - 19:00",
  },
  {
    id: "s29",
    name: "Antiquités Africaines",
    description: "Boutique d'antiquités et objets de collection africains. Pièces rares et authentiques.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 178,
    country_origin: "Bénin",
    category: "Antiquités",
    status: "open",
    delivery_available: false,
    verified: true,
    opening_hours: "11:00 - 18:00",
  },
  {
    id: "s30",
    name: "Épicerie Fine Africaine",
    description: "Épicerie fine spécialisée dans les produits d'exception. Huiles rares, condiments et délicatesses.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 245,
    country_origin: "Maroc",
    category: "Épicerie Fine",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s31",
    name: "Instruments de Musique",
    description: "Magasin d'instruments de musique africains. Djembés, koras, balafons et percussions.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 189,
    country_origin: "Guinée",
    category: "Musique",
    status: "open",
    delivery_available: true,
    verified: true,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s32",
    name: "Thé Africain",
    description: "Boutique de thés africains. Rooibos, thé vert marocain et infusions traditionnelles.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 212,
    country_origin: "Afrique du Sud",
    category: "Café & Thé",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "9:00 - 19:00",
  },
  {
    id: "s33",
    name: "Lingerie Africaine",
    description: "Boutique de lingerie et sous-vêtements. Collections adaptées aux morphologies africaines.",
    type: "store",
    image_url: "/african-fabrics.jpg",
    rating: 4.6,
    review_count: 167,
    country_origin: "Sénégal",
    category: "Lingerie",
    status: "open",
    delivery_available: true,
    verified: false,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s34",
    name: "Chocolaterie Africaine",
    description: "Chocolaterie artisanale utilisant du cacao africain. Chocolats fins et pralinés.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 234,
    country_origin: "Côte d'Ivoire",
    category: "Chocolaterie",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s35",
    name: "Optique Africaine",
    description: "Opticien spécialisé dans les montures africaines. Lunettes de vue et solaires design.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 178,
    country_origin: "Ghana",
    category: "Optique",
    status: "open",
    delivery_available: false,
    verified: true,
    opening_hours: "9:00 - 19:00",
  },
  {
    id: "s36",
    name: "Épicerie Halal",
    description: "Épicerie halal certifiée. Viandes, charcuterie et produits alimentaires halal.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 289,
    country_origin: "Maroc",
    category: "Halal",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "8:00 - 21:00",
  },
  {
    id: "s37",
    name: "Librairie Islamique",
    description: "Librairie spécialisée dans les livres islamiques. Corans, livres religieux et éducatifs.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.6,
    review_count: 156,
    country_origin: "Égypte",
    category: "Librairie",
    status: "open",
    delivery_available: true,
    verified: true,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s38",
    name: "Fruits Exotiques",
    description: "Primeur spécialisé dans les fruits exotiques. Mangues, papayes, fruits de la passion et plus.",
    type: "store",
    image_url: "/african-produce.jpg",
    rating: 4.7,
    review_count: 223,
    country_origin: "Cameroun",
    category: "Fruits & Légumes",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "7:00 - 20:00",
  },
  {
    id: "s39",
    name: "Tapis Africains",
    description: "Boutique de tapis et kilims africains. Tapis berbères, touaregs et contemporains.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 189,
    country_origin: "Maroc",
    category: "Décoration",
    status: "open",
    delivery_available: false,
    verified: true,
    opening_hours: "10:00 - 18:00",
  },
  {
    id: "s40",
    name: "Épicerie Végétarienne",
    description: "Épicerie végétarienne africaine. Légumineuses, céréales et alternatives végétales.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 201,
    country_origin: "Éthiopie",
    category: "Végétarien",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "9:00 - 19:00",
  },
  {
    id: "s41",
    name: "Céramique Africaine",
    description: "Atelier de céramique africaine. Poteries, vaisselle et objets décoratifs artisanaux.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.7,
    review_count: 167,
    country_origin: "Mali",
    category: "Artisanat",
    status: "open",
    delivery_available: false,
    verified: true,
    opening_hours: "10:00 - 18:00",
  },
  {
    id: "s42",
    name: "Épicerie Sans Gluten",
    description:
      "Épicerie spécialisée dans les produits sans gluten d'origine africaine. Farines alternatives et snacks.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.8,
    review_count: 178,
    country_origin: "Nigeria",
    category: "Sans Gluten",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "9:00 - 19:00",
  },
  {
    id: "s43",
    name: "Vannerie Africaine",
    description: "Boutique de vannerie et objets tressés. Paniers, corbeilles et accessoires artisanaux.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.6,
    review_count: 145,
    country_origin: "Sénégal",
    category: "Artisanat",
    status: "open",
    delivery_available: true,
    verified: false,
    opening_hours: "10:00 - 18:00",
  },
  {
    id: "s44",
    name: "Épicerie Vegan",
    description: "Épicerie vegan africaine. Produits 100% végétaux inspirés des traditions africaines.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 212,
    country_origin: "Ghana",
    category: "Vegan",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "9:00 - 19:00",
  },
  {
    id: "s45",
    name: "Textiles Traditionnels",
    description: "Boutique de textiles africains traditionnels. Kente, mudcloth et tissus cérémoniels.",
    type: "store",
    image_url: "/african-fabrics.jpg",
    rating: 4.8,
    review_count: 234,
    country_origin: "Ghana",
    category: "Textiles",
    status: "open",
    delivery_available: true,
    verified: true,
    opening_hours: "10:00 - 19:00",
  },
  {
    id: "s46",
    name: "Épicerie du Monde",
    description: "Épicerie internationale avec large sélection africaine. Produits de tous les pays d'Afrique.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 289,
    country_origin: "Multi-pays",
    category: "Épicerie",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "8:00 - 21:00",
  },
  {
    id: "s47",
    name: "Perles Africaines",
    description: "Boutique de perles et accessoires de bijouterie. Perles traditionnelles et matériaux pour création.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.6,
    review_count: 156,
    country_origin: "Kenya",
    category: "Bijouterie",
    status: "open",
    delivery_available: true,
    verified: false,
    opening_hours: "10:00 - 18:00",
  },
  {
    id: "s48",
    name: "Épicerie Solidaire",
    description: "Épicerie solidaire proposant des produits africains issus du commerce équitable.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.9,
    review_count: 267,
    country_origin: "Multi-pays",
    category: "Commerce Équitable",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "9:00 - 19:00",
  },
  {
    id: "s49",
    name: "Masques Africains",
    description: "Galerie spécialisée dans les masques africains authentiques. Pièces de collection et décoratives.",
    type: "store",
    image_url: "/african-crafts.jpg",
    rating: 4.8,
    review_count: 178,
    country_origin: "Côte d'Ivoire",
    category: "Art",
    status: "open",
    delivery_available: false,
    verified: true,
    opening_hours: "11:00 - 18:00",
  },
  {
    id: "s50",
    name: "Épicerie du Terroir",
    description: "Épicerie valorisant les produits du terroir africain. Spécialités régionales et produits artisanaux.",
    type: "store",
    image_url: "/african-grocery.jpg",
    rating: 4.7,
    review_count: 223,
    country_origin: "Multi-pays",
    category: "Terroir",
    status: "open",
    delivery_available: true,
    click_collect: true,
    verified: true,
    opening_hours: "9:00 - 19:00",
  },
]
