export type MenuItem = {
  id: string
  restaurant_id: string
  name: string
  description: string
  price: number
  category: string
  image_url: string
  rating: number
  review_count: number
  is_popular?: boolean
  is_vegetarian?: boolean
  is_spicy?: boolean
  allergens?: string[]
}

export const MOCK_MENU_ITEMS: MenuItem[] = [
  // Restaurant r1 - Mama Africa Restaurant (Sénégal)
  {
    id: "m1",
    restaurant_id: "r1",
    name: "Thiéboudienne Rouge",
    description: "Riz au poisson, légumes et sauce tomate épicée - plat national sénégalais",
    price: 16.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.9,
    review_count: 34,
    is_popular: true,
    is_spicy: true,
  },
  {
    id: "m2",
    restaurant_id: "r1",
    name: "Poulet Yassa",
    description: "Poulet mariné aux oignons caramélisés, citron et moutarde, servi avec du riz",
    price: 14.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.8,
    review_count: 28,
    is_popular: true,
  },
  {
    id: "m3",
    restaurant_id: "r1",
    name: "Mafé au Bœuf",
    description: "Ragoût de bœuf à la sauce d'arachide, légumes et riz blanc",
    price: 15.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.7,
    review_count: 22,
  },
  {
    id: "m4",
    restaurant_id: "r1",
    name: "Pastels au Poisson",
    description: "Beignets de poisson épicés, frits et croustillants",
    price: 6.99,
    category: "Entrées",
    image_url: "/african-restaurant.png",
    rating: 4.6,
    review_count: 45,
    is_popular: true,
  },
  {
    id: "m5",
    restaurant_id: "r1",
    name: "Salade Niébé",
    description: "Salade de haricots niébé, tomates, oignons et vinaigrette citronnée",
    price: 7.99,
    category: "Entrées",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.5,
    review_count: 18,
    is_vegetarian: true,
  },
  {
    id: "m6",
    restaurant_id: "r1",
    name: "Yassa Poisson",
    description: "Poisson grillé mariné aux oignons et citron",
    price: 17.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.8,
    review_count: 31,
    is_popular: true,
  },
  {
    id: "m7",
    restaurant_id: "r1",
    name: "Thiéré Bassi Salté",
    description: "Couscous sénégalais au lait caillé et raisins secs",
    price: 8.99,
    category: "Desserts",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.7,
    review_count: 25,
  },
  {
    id: "m8",
    restaurant_id: "r1",
    name: "Bissap Frais",
    description: "Jus d'hibiscus maison, frais et désaltérant",
    price: 4.99,
    category: "Boissons",
    image_url: "/african-restaurant.png",
    rating: 4.9,
    review_count: 52,
    is_popular: true,
  },
  {
    id: "m9",
    restaurant_id: "r1",
    name: "Thiébou Yapp",
    description: "Riz à la viande, légumes et sauce tomate",
    price: 15.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.6,
    review_count: 19,
  },
  {
    id: "m10",
    restaurant_id: "r1",
    name: "Accara",
    description: "Beignets de haricots épicés, croustillants à l'extérieur",
    price: 5.99,
    category: "Entrées",
    image_url: "/african-restaurant.png",
    rating: 4.5,
    review_count: 27,
    is_vegetarian: true,
  },

  // Menus génériques pour tous les autres restaurants (40 items)
  {
    id: "m11",
    restaurant_id: "r2",
    name: "Tô Sauce Gombo",
    description: "Pâte de mil servie avec une sauce gombo onctueuse",
    price: 12.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.7,
    review_count: 23,
    is_vegetarian: true,
  },
  {
    id: "m12",
    restaurant_id: "r2",
    name: "Riz Gras Malien",
    description: "Riz cuisiné avec viande, légumes et épices locales",
    price: 14.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.8,
    review_count: 31,
    is_popular: true,
  },
  {
    id: "m13",
    restaurant_id: "r3",
    name: "Thiéboudienne Blanche",
    description: "Riz au poisson sans tomate, version traditionnelle",
    price: 16.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.9,
    review_count: 42,
    is_popular: true,
  },
  {
    id: "m14",
    restaurant_id: "r3",
    name: "Mafé Poulet",
    description: "Poulet mijoté dans une sauce d'arachide crémeuse",
    price: 13.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 28,
  },
  {
    id: "m15",
    restaurant_id: "r4",
    name: "Attiéké Poisson Braisé",
    description: "Semoule de manioc avec poisson grillé et sauce pimentée",
    price: 15.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.8,
    review_count: 35,
    is_popular: true,
    is_spicy: true,
  },
  {
    id: "m16",
    restaurant_id: "r4",
    name: "Alloco Sauce Piment",
    description: "Bananes plantains frites avec sauce tomate épicée",
    price: 7.99,
    category: "Entrées",
    image_url: "/african-restaurant.png",
    rating: 4.6,
    review_count: 41,
    is_vegetarian: true,
    is_spicy: true,
  },
  {
    id: "m17",
    restaurant_id: "r5",
    name: "Ndolé",
    description: "Feuilles de ndolé mijotées avec arachides et viande",
    price: 16.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.9,
    review_count: 38,
    is_popular: true,
  },
  {
    id: "m18",
    restaurant_id: "r5",
    name: "Poulet DG",
    description: "Poulet sauté aux légumes et plantains, style Directeur Général",
    price: 18.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.8,
    review_count: 33,
    is_popular: true,
  },
  {
    id: "m19",
    restaurant_id: "r6",
    name: "Doro Wat",
    description: "Ragoût de poulet épicé éthiopien servi avec injera",
    price: 17.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.9,
    review_count: 45,
    is_popular: true,
    is_spicy: true,
  },
  {
    id: "m20",
    restaurant_id: "r6",
    name: "Kitfo",
    description: "Bœuf haché cru assaisonné au beurre épicé",
    price: 19.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 29,
    is_spicy: true,
  },
  {
    id: "m21",
    restaurant_id: "r7",
    name: "Jollof Rice Nigérian",
    description: "Riz parfumé cuit dans une sauce tomate épicée",
    price: 13.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.8,
    review_count: 52,
    is_popular: true,
    is_spicy: true,
  },
  {
    id: "m22",
    restaurant_id: "r7",
    name: "Suya",
    description: "Brochettes de bœuf épicées grillées",
    price: 12.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 38,
    is_spicy: true,
  },
  {
    id: "m23",
    restaurant_id: "r8",
    name: "Couscous Royal",
    description: "Couscous avec agneau, poulet, merguez et légumes",
    price: 22.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.9,
    review_count: 61,
    is_popular: true,
  },
  {
    id: "m24",
    restaurant_id: "r8",
    name: "Tajine d'Agneau",
    description: "Agneau mijoté aux pruneaux et amandes",
    price: 19.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.8,
    review_count: 44,
  },
  {
    id: "m25",
    restaurant_id: "r9",
    name: "Banku et Tilapia",
    description: "Pâte de maïs fermentée avec poisson tilapia grillé",
    price: 15.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.6,
    review_count: 27,
  },
  {
    id: "m26",
    restaurant_id: "r9",
    name: "Fufu Soupe Cacahuète",
    description: "Fufu de manioc avec soupe d'arachide",
    price: 14.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 31,
  },
  {
    id: "m27",
    restaurant_id: "r10",
    name: "Pilau de Zanzibar",
    description: "Riz épicé aux fruits de mer et épices swahili",
    price: 21.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.9,
    review_count: 39,
    is_popular: true,
    is_spicy: true,
  },
  {
    id: "m28",
    restaurant_id: "r10",
    name: "Biryani Tanzanien",
    description: "Riz basmati aux épices et viande marinée",
    price: 18.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.8,
    review_count: 33,
    is_spicy: true,
  },
  {
    id: "m29",
    restaurant_id: "r11",
    name: "Ceebu Jën",
    description: "Riz au poisson version traditionnelle dakaroise",
    price: 14.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.7,
    review_count: 28,
  },
  {
    id: "m30",
    restaurant_id: "r11",
    name: "Dibi",
    description: "Agneau grillé mariné aux épices sénégalaises",
    price: 16.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.8,
    review_count: 35,
    is_popular: true,
  },
  {
    id: "m31",
    restaurant_id: "r12",
    name: "Poisson Braisé",
    description: "Poisson entier grillé avec sauce pimentée",
    price: 18.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.8,
    review_count: 31,
    is_spicy: true,
  },
  {
    id: "m32",
    restaurant_id: "r12",
    name: "Poulet Moambé",
    description: "Poulet mijoté dans une sauce de noix de palme",
    price: 15.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 26,
  },
  {
    id: "m33",
    restaurant_id: "r13",
    name: "Brik à l'Œuf",
    description: "Feuille de brick croustillante farcie à l'œuf et thon",
    price: 6.99,
    category: "Entrées",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.6,
    review_count: 42,
    is_popular: true,
  },
  {
    id: "m34",
    restaurant_id: "r13",
    name: "Couscous Tunisien",
    description: "Couscous aux légumes et viande d'agneau",
    price: 13.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 29,
  },
  {
    id: "m35",
    restaurant_id: "r14",
    name: "Tiguadégué Na",
    description: "Ragoût d'arachide avec viande et légumes",
    price: 17.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.9,
    review_count: 37,
    is_popular: true,
  },
  {
    id: "m36",
    restaurant_id: "r14",
    name: "Capitaine Braisé",
    description: "Poisson capitaine grillé aux épices maliennes",
    price: 19.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.8,
    review_count: 32,
  },
  {
    id: "m37",
    restaurant_id: "r15",
    name: "Braai Mixte",
    description: "Assortiment de viandes grillées sud-africaines",
    price: 24.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.9,
    review_count: 48,
    is_popular: true,
  },
  {
    id: "m38",
    restaurant_id: "r15",
    name: "Bobotie",
    description: "Hachis de viande épicé gratiné aux œufs",
    price: 16.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 34,
    is_spicy: true,
  },
  {
    id: "m39",
    restaurant_id: "r16",
    name: "Riz Sauce Feuilles",
    description: "Riz avec sauce aux feuilles de manioc",
    price: 12.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.6,
    review_count: 24,
  },
  {
    id: "m40",
    restaurant_id: "r16",
    name: "Poulet Kedjenou",
    description: "Poulet mijoté aux légumes dans une canari",
    price: 14.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 28,
  },
  {
    id: "m41",
    restaurant_id: "r17",
    name: "Koshari",
    description: "Mélange de riz, lentilles, pâtes et sauce tomate",
    price: 11.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.8,
    review_count: 45,
    is_popular: true,
    is_vegetarian: true,
  },
  {
    id: "m42",
    restaurant_id: "r17",
    name: "Falafel Égyptien",
    description: "Boulettes de fèves frites, croustillantes",
    price: 8.99,
    category: "Entrées",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 38,
    is_vegetarian: true,
  },
  {
    id: "m43",
    restaurant_id: "r18",
    name: "Nyama Choma",
    description: "Viande de chèvre grillée, spécialité kényane",
    price: 19.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.9,
    review_count: 41,
    is_popular: true,
  },
  {
    id: "m44",
    restaurant_id: "r18",
    name: "Ugali Sukuma Wiki",
    description: "Pâte de maïs avec légumes verts sautés",
    price: 13.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.6,
    review_count: 27,
    is_vegetarian: true,
  },
  {
    id: "m45",
    restaurant_id: "r19",
    name: "Riz Gras Burkinabé",
    description: "Riz cuisiné avec viande et légumes locaux",
    price: 12.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.5,
    review_count: 22,
  },
  {
    id: "m46",
    restaurant_id: "r19",
    name: "Tô Sauce Arachide",
    description: "Pâte de mil avec sauce d'arachide",
    price: 11.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.6,
    review_count: 19,
  },
  {
    id: "m47",
    restaurant_id: "r20",
    name: "Couscous Algérien",
    description: "Couscous traditionnel aux sept légumes",
    price: 18.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.8,
    review_count: 52,
    is_popular: true,
  },
  {
    id: "m48",
    restaurant_id: "r20",
    name: "Tajine Merguez",
    description: "Tajine de merguez aux légumes",
    price: 16.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 36,
    is_spicy: true,
  },
  {
    id: "m49",
    restaurant_id: "r21",
    name: "Fufu Sauce Gombo",
    description: "Fufu de manioc avec sauce gombo",
    price: 13.99,
    category: "Plats principaux",
    image_url: "/vibrant-jollof-rice.png",
    rating: 4.6,
    review_count: 25,
  },
  {
    id: "m50",
    restaurant_id: "r21",
    name: "Akoumé Poisson",
    description: "Pâte de maïs avec poisson en sauce",
    price: 14.99,
    category: "Plats principaux",
    image_url: "/african-restaurant.png",
    rating: 4.7,
    review_count: 28,
  },
]
